import 'package:flutter/material.dart';

// Hot Pink and Gold Gradient එක සඳහා Decoration එක
const BoxDecoration kCategoryDecoration = BoxDecoration(
  shape: BoxShape.circle,
  gradient: LinearGradient(
    colors: [Color(0xFFFF1493), Color(0xFFD4AF37)],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  ),
);

// බෑග් වර්ග (Bags)
final List<Map<String, String>> bagItems = [
  
  {'name': 'Hand Bag', 'price': 'LKR 3,450.00', 'image': 'assets/Bags/HB 1.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,500.00', 'image': 'assets/Bags/HB 2.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,200.00', 'image': 'assets/Bags/HB 3.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,150.00', 'image': 'assets/Bags/HB 4.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,550.00', 'image': 'assets/Bags/HB 5.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,350.00', 'image': 'assets/Bags/HB 6.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,450.00', 'image': 'assets/Bags/HB 7.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,230.00', 'image': 'assets/Bags/HB 8.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,375.00', 'image': 'assets/Bags/HB 9.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,575.00', 'image': 'assets/Bags/HB 10.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,000.00', 'image': 'assets/Bags/HB 11.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,450.00', 'image': 'assets/Bags/HB 12.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 2,900.00', 'image': 'assets/Bags/HB 13.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,350.00', 'image': 'assets/Bags/HB 14.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,250.00', 'image': 'assets/Bags/HB 15.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 2,000.00', 'image': 'assets/Bags/HB 16.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 2,850.00', 'image': 'assets/Bags/HB 17.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 2,950.00', 'image': 'assets/Bags/HB 18.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,475.00', 'image': 'assets/Bags/HB 19.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,500.00', 'image': 'assets/Bags/HB 20.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,350.00', 'image': 'assets/Bags/HB 21.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,340.00', 'image': 'assets/Bags/HB 22.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 1,500.00', 'image': 'assets/Bags/HB 23.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 2,450.00', 'image': 'assets/Bags/HB 24.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 2,950.00', 'image': 'assets/Bags/HB 25.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 3,150.00', 'image': 'assets/Bags/HB 26.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 2,850.00', 'image': 'assets/Bags/HB 27.jpg', 'type': 'Bags'},
  {'name': 'Hand Bag', 'price': 'LKR 2,250.00', 'image': 'assets/Bags/HB 28.jpg', 'type': 'Bags'},
  {'name': 'Clutches', 'price': 'LKR 2,450.00', 'image': 'assets/Bags/C 1.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 2,575.00', 'image': 'assets/Bags/C 2.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,450.00', 'image': 'assets/Bags/C 3.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,100.00', 'image': 'assets/Bags/C 4.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,250.00', 'image': 'assets/Bags/C 5.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 2,950.00', 'image': 'assets/Bags/C 6.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 2,850.00', 'image': 'assets/Bags/C 7.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,275.00', 'image': 'assets/Bags/C 8.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,450.00', 'image': 'assets/Bags/C 9.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,350.00', 'image': 'assets/Bags/C 10.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,255.00', 'image': 'assets/Bags/C 11.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,650.00', 'image': 'assets/Bags/C 12.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,550.00', 'image': 'assets/Bags/C 13.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,470.00', 'image': 'assets/Bags/C 14.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,120.00', 'image': 'assets/Bags/C 15.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 2,750.00', 'image': 'assets/Bags/C 16.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 2,850.00', 'image': 'assets/Bags/C 17.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,220.00', 'image': 'assets/Bags/C 18.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,440.00', 'image': 'assets/Bags/C 19.jpg', 'type': 'Clutches'},
  {'name': 'Clutches', 'price': 'LKR 3,350.00', 'image': 'assets/Bags/C 20.jpg', 'type': 'Clutches'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,200.00', 'image': 'assets/Bags/W 1.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,300.00', 'image': 'assets/Bags/W 2.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,250.00', 'image': 'assets/Bags/W 3.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 2,200.00', 'image': 'assets/Bags/W 4.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,700.00', 'image': 'assets/Bags/W 5.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,500.00', 'image': 'assets/Bags/W 6.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,600.00', 'image': 'assets/Bags/W 7.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,200.00', 'image': 'assets/Bags/W 8.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,2900.00', 'image': 'assets/Bags/W 9.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,950.00', 'image': 'assets/Bags/W 10.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,850.00', 'image': 'assets/Bags/W 11.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,650.00', 'image': 'assets/Bags/W 12.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,700.00', 'image': 'assets/Bags/W 13.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,240.00', 'image': 'assets/Bags/W 14.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,575.00', 'image': 'assets/Bags/W 15.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,350.00', 'image': 'assets/Bags/W 16.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,480.00', 'image': 'assets/Bags/W 17.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,540.00', 'image': 'assets/Bags/W 18.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,820.00', 'image': 'assets/Bags/W 19.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,390.00', 'image': 'assets/Bags/W 20.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,470.00', 'image': 'assets/Bags/W 21.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,690.00', 'image': 'assets/Bags/W 22.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,850.00', 'image': 'assets/Bags/W 23.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,560.00', 'image': 'assets/Bags/W 24.jpg', 'type': 'Wallets'},
  {'name': 'Casual Wallet', 'price': 'LKR 1,670.00', 'image': 'assets/Bags/W 25.jpg', 'type': 'Wallets'},
  {'name': 'Backpack', 'price': 'LKR 4,500.00', 'image': 'assets/Bags/B 1.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,500.00', 'image': 'assets/Bags/B 2.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,575.00', 'image': 'assets/Bags/B 3.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,400.00', 'image': 'assets/Bags/B 4.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,570.00', 'image': 'assets/Bags/B 5.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,230.00', 'image': 'assets/Bags/B 6.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,480.00', 'image': 'assets/Bags/B 7.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,900.00', 'image': 'assets/Bags/B 8.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,500.00', 'image': 'assets/Bags/B 9.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,600.00', 'image': 'assets/Bags/B 10.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 2,850.00', 'image': 'assets/Bags/B 11.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,975.00', 'image': 'assets/Bags/B 12.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,780.00', 'image': 'assets/Bags/B 13.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,560.00', 'image': 'assets/Bags/B 14.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,500.00', 'image': 'assets/Bags/B 15.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,675.00', 'image': 'assets/Bags/B 16.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,890.00', 'image': 'assets/Bags/B 17.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,250.00', 'image': 'assets/Bags/B 18.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,600.00', 'image': 'assets/Bags/B 19.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,680.00', 'image': 'assets/Bags/B 20.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,350.00', 'image': 'assets/Bags/B 21.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,990.00', 'image': 'assets/Bags/B 22.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,660.00', 'image': 'assets/Bags/B 23.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,559.00', 'image': 'assets/Bags/B 24.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,568.00', 'image': 'assets/Bags/B 25.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 2,980.00', 'image': 'assets/Bags/B 26.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 2,860.00', 'image': 'assets/Bags/B 27.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,500.00', 'image': 'assets/Bags/B 28.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 4,400.00', 'image': 'assets/Bags/B 29.jpg', 'type': 'Backpacks'},
  {'name': 'Backpack', 'price': 'LKR 3,900.00', 'image': 'assets/Bags/B 30.jpg', 'type': 'Backpacks'},
];

// කාන්තා ඇඳුම් (Womens)
final List<Map<String, String>> womensItems = [
  {'name': 'Floral Blouse', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/B 1.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,250.00', 'image': 'assets/Womens/B 2.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,375.00', 'image': 'assets/Womens/B 3.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 3,150.00', 'image': 'assets/Womens/B 4.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 3,125.00', 'image': 'assets/Womens/B 5.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 1,985.00', 'image': 'assets/Womens/B 6.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,340.00', 'image': 'assets/Womens/B 7.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/B 8.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 1,875.00', 'image': 'assets/Womens/B 9.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,650.00', 'image': 'assets/Womens/B 10.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,575.00', 'image': 'assets/Womens/B 11.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,682.00', 'image': 'assets/Womens/B 12.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,960.00', 'image': 'assets/Womens/B 13.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,350.00', 'image': 'assets/Womens/B 14.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 1,950.00', 'image': 'assets/Womens/B 15.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,155.00', 'image': 'assets/Womens/B 16.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 1,750.00', 'image': 'assets/Womens/B 17.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 3,150.00', 'image': 'assets/Womens/B 18.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 1,650.00', 'image': 'assets/Womens/B 19.jpg', 'type': 'Blouses'},
  {'name': 'Floral Blouse', 'price': 'LKR 2,350.00', 'image': 'assets/Womens/B 20.jpg', 'type': 'Blouses'},
  {'name': 'Croptops', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/C 1.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,350.00', 'image': 'assets/Womens/C 2.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,150.00', 'image': 'assets/Womens/C 3.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,050.00', 'image': 'assets/Womens/C 4.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,550.00', 'image': 'assets/Womens/C 5.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,650.00', 'image': 'assets/Womens/C 6.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,950.00', 'image': 'assets/Womens/C 7.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/C 8.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,175.00', 'image': 'assets/Womens/C 9.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,900.00', 'image': 'assets/Womens/C 10.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,345.00', 'image': 'assets/Womens/C 11.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,285.00', 'image': 'assets/Womens/C 12.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,875.00', 'image': 'assets/Womens/C 13.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,678.00', 'image': 'assets/Womens/C 14.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,250.00', 'image': 'assets/Womens/C 15.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,465.00', 'image': 'assets/Womens/C 16.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 2,382.00', 'image': 'assets/Womens/C 17.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,895.00', 'image': 'assets/Womens/C 18.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,450.00', 'image': 'assets/Womens/C 19.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,550.00', 'image': 'assets/Womens/C 20.jpg', 'type': 'Croptops'},
  {'name': 'Croptops', 'price': 'LKR 1,350.00', 'image': 'assets/Womens/C 21.jpg', 'type': 'Croptops'},
  {'name': 'Denims', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/D 1.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,580.00', 'image': 'assets/Womens/D 2.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,150.00', 'image': 'assets/Womens/D 3.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 2,650.00', 'image': 'assets/Womens/D 4.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 2,850.00', 'image': 'assets/Womens/D 5.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,250.00', 'image': 'assets/Womens/D 5.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/D 7.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,850.00', 'image': 'assets/Womens/D 8.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,650.00', 'image': 'assets/Womens/D 9.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 1,875.00', 'image': 'assets/Womens/D 10.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 2,993.00', 'image': 'assets/Womens/D 11.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,684.00', 'image': 'assets/Womens/D 12.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,150.00', 'image': 'assets/Womens/D 13.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 4,150.00', 'image': 'assets/Womens/D 14.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,850.00', 'image': 'assets/Womens/D 15.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 5,150.00', 'image': 'assets/Womens/D 16.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 4,560.00', 'image': 'assets/Womens/D 17.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 5,000.00', 'image': 'assets/Womens/D 18.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,760.00', 'image': 'assets/Womens/D 19.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 4,750.00', 'image': 'assets/Womens/D 20.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 4,375.00', 'image': 'assets/Womens/D 21.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 2,000.00', 'image': 'assets/Womens/D 22.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 2,870.00', 'image': 'assets/Womens/D 23.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 2,990.00', 'image': 'assets/Womens/D 24.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 1,950.00', 'image': 'assets/Womens/D 25.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 3,170.00', 'image': 'assets/Womens/D 26.jpg', 'type': 'Denim'},
  {'name': 'Denims', 'price': 'LKR 2,450.00', 'image': 'assets/Womens/D 27.jpg', 'type': 'Denim'},
  {'name': 'Frocks', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/F 1.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 3,150.00', 'image': 'assets/Womens/F 2.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,450.00', 'image': 'assets/Womens/F 3.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,985.00', 'image': 'assets/Womens/F 4.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/F 5.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,750.00', 'image': 'assets/Womens/F 6.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,650.00', 'image': 'assets/Womens/F 7.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/F 8.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 3,100.00', 'image': 'assets/Womens/F 9.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,550.00', 'image': 'assets/Womens/F 10.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,560.00', 'image': 'assets/Womens/F 11.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,750.00', 'image': 'assets/Womens/F 12.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,950.00', 'image': 'assets/Womens/F 13.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,350.00', 'image': 'assets/Womens/F 14.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,275.00', 'image': 'assets/Womens/F 15.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,450.00', 'image': 'assets/Womens/F 16.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,550.00', 'image': 'assets/Womens/F 17.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,660.00', 'image': 'assets/Womens/F 18.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,940.00', 'image': 'assets/Womens/F 19.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,300.00', 'image': 'assets/Womens/F 20.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,955.00', 'image': 'assets/Womens/F 21.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 3,150.00', 'image': 'assets/Womens/F 22.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,450.00', 'image': 'assets/Womens/F 23.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,950.00', 'image': 'assets/Womens/F 24.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,880.00', 'image': 'assets/Womens/F 25.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,770.00', 'image': 'assets/Womens/F 26.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,660.00', 'image': 'assets/Womens/F 27.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,580.00', 'image': 'assets/Womens/F 28.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/F 29.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,220.00', 'image': 'assets/Womens/F 30.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,140.00', 'image': 'assets/Womens/F 31.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/F 32.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,250.00', 'image': 'assets/Womens/F 33.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,4800.00', 'image': 'assets/Womens/F 34.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,875.00', 'image': 'assets/Womens/F 35.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,170.00', 'image': 'assets/Womens/F 36.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,950.00', 'image': 'assets/Womens/F 37.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 1,925.00', 'image': 'assets/Womens/F 38.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,650.00', 'image': 'assets/Womens/F 39.jpg', 'type': 'Frocks'},
  {'name': 'Frocks', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/F 40.jpg', 'type': 'Frocks'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/K 1.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,000.00', 'image': 'assets/Womens/K 2.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 1,550.00', 'image': 'assets/Womens/K 3.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,350.00', 'image': 'assets/Womens/K 4.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,250.00', 'image': 'assets/Womens/K 5.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/K 6.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,450.00', 'image': 'assets/Womens/K 7.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,355.00', 'image': 'assets/Womens/K 8.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,100.00', 'image': 'assets/Womens/K 9.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 1,880.00', 'image': 'assets/Womens/K 10.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/K 11.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 1,950.00', 'image': 'assets/Womens/K 12.jpg', 'type': 'Cargo Pants'},
  {'name': 'Cargo Pants', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/K 13.jpg', 'type': 'Cargo Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,000.00', 'image': 'assets/Womens/O 1.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/O 2.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,800.00', 'image': 'assets/Womens/O 3.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,100.00', 'image': 'assets/Womens/O 4.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/O 5.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,950.00', 'image': 'assets/Womens/O 6.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,875.00', 'image': 'assets/Womens/O 7.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,750.00', 'image': 'assets/Womens/O 8.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,790.00', 'image': 'assets/Womens/O 9.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,250.00', 'image': 'assets/Womens/O 10.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,350.00', 'image': 'assets/Womens/O 11.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,650.00', 'image': 'assets/Womens/O 12.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,375.00', 'image': 'assets/Womens/O 13.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,050.00', 'image': 'assets/Womens/O 14.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,450.00', 'image': 'assets/Womens/O 15.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,475.00', 'image': 'assets/Womens/O 16.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,975.00', 'image': 'assets/Womens/O 17.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 1,990.00', 'image': 'assets/Womens/O 18.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,240.00', 'image': 'assets/Womens/O 19.jpg', 'type': 'Office Pants'},
  {'name': 'Office Pants', 'price': 'LKR 2,100.00', 'image': 'assets/Womens/O 20.jpg', 'type': 'Office Pants'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/S 1.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,950.00', 'image': 'assets/Womens/S 2.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,750.00', 'image': 'assets/Womens/S 3.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,650.00', 'image': 'assets/Womens/S 4.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,875.00', 'image': 'assets/Womens/S 5.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,990.00', 'image': 'assets/Womens/S 6.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,690.00', 'image': 'assets/Womens/S 7.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/S 8.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,000.00', 'image': 'assets/Womens/S 9.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,150.00', 'image': 'assets/Womens/S 10.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,250.00', 'image': 'assets/Womens/S 11.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,225.00', 'image': 'assets/Womens/S 12.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,100.00', 'image': 'assets/Womens/S 13.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,870.00', 'image': 'assets/Womens/S 14.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,980.00', 'image': 'assets/Womens/S 15.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,750.00', 'image': 'assets/Womens/S 16.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,675.00', 'image': 'assets/Womens/S 17.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,970.00', 'image': 'assets/Womens/S 18.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,100.00', 'image': 'assets/Womens/S 19.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,250.00', 'image': 'assets/Womens/S 20.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,820.00', 'image': 'assets/Womens/S 21.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,860.00', 'image': 'assets/Womens/S 22.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,880.00', 'image': 'assets/Womens/S 23.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,900.00', 'image': 'assets/Womens/S 24.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,920.00', 'image': 'assets/Womens/S 25.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,120.00', 'image': 'assets/Womens/S 26.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 2,225.00', 'image': 'assets/Womens/S 27.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,750.00', 'image': 'assets/Womens/S 28.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,870.00', 'image': 'assets/Womens/S 29.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,995.00', 'image': 'assets/Womens/S 30.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,725.00', 'image': 'assets/Womens/S 31.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/S 32.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,650.00', 'image': 'assets/Womens/S 33.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,900.00', 'image': 'assets/Womens/S 34.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,820.00', 'image': 'assets/Womens/S 35.jpg', 'type': 'Skirts'},
  {'name': 'Casual Skirt', 'price': 'LKR 1,850.00', 'image': 'assets/Womens/S 36.jpg', 'type': 'Skirts'},
];

// පිරිමි ඇඳුම් (Mens)
final List<Map<String, String>> mensItems = [
  {'name': 'Formal Shirt', 'price': 'LKR 2,900.00', 'image': 'assets/Mens/S 1.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 1,900.00', 'image': 'assets/Mens/S 2.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 1,950.00', 'image': 'assets/Mens/S 3.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 1,870.00', 'image': 'assets/Mens/S 4.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,450.00', 'image': 'assets/Mens/S 5.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,550.00', 'image': 'assets/Mens/S 6.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,300.00', 'image': 'assets/Mens/S 7.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,800.00', 'image': 'assets/Mens/S 8.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,700.00', 'image': 'assets/Mens/S 9.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,960.00', 'image': 'assets/Mens/S 10.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,690.00', 'image': 'assets/Mens/S 11.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,920.00', 'image': 'assets/Mens/S 12.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,875.00', 'image': 'assets/Mens/S 13.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 1,900.00', 'image': 'assets/Mens/S 14.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,750.00', 'image': 'assets/Mens/S 15.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 1,880.00', 'image': 'assets/Mens/S 16.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,990.00', 'image': 'assets/Mens/S 17.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,975.00', 'image': 'assets/Mens/S 18.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,600.00', 'image': 'assets/Mens/S 19.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,900.00', 'image': 'assets/Mens/S 20.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,600.00', 'image': 'assets/Mens/S 21.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,500.00', 'image': 'assets/Mens/S 22.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,900.00', 'image': 'assets/Mens/S 23.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,970.00', 'image': 'assets/Mens/S 24.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,760.00', 'image': 'assets/Mens/S 25.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,660.00', 'image': 'assets/Mens/S 26.jpg', 'type': 'Shirts'},
  {'name': 'Formal Shirt', 'price': 'LKR 2,900.00', 'image': 'assets/Mens/S 27.jpg', 'type': 'Shirts'},
  {'name': 'Trousers', 'price': 'LKR 2,700.00', 'image': 'assets/Mens/R 1.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,700.00', 'image': 'assets/Mens/R 2.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,750.00', 'image': 'assets/Mens/R 3.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,600.00', 'image': 'assets/Mens/R 4.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,800.00', 'image': 'assets/Mens/R 5.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,900.00', 'image': 'assets/Mens/R 6.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,775.00', 'image': 'assets/Mens/R 7.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,660.00', 'image': 'assets/Mens/R 8.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,860.00', 'image': 'assets/Mens/R 9.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,7800.00', 'image': 'assets/Mens/R 10.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 1,990.00', 'image': 'assets/Mens/R 11.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,700.00', 'image': 'assets/Mens/R 12.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,800.00', 'image': 'assets/Mens/R 13.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,780.00', 'image': 'assets/Mens/R 14.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,600.00', 'image': 'assets/Mens/R 15.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 1,990.00', 'image': 'assets/Mens/R 16.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,900.00', 'image': 'assets/Mens/R 17.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,200.00', 'image': 'assets/Mens/R 18.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 4,300.00', 'image': 'assets/Mens/R 19.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,700.00', 'image': 'assets/Mens/R 20.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,890.00', 'image': 'assets/Mens/R 21.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,500.00', 'image': 'assets/Mens/R 22.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,700.00', 'image': 'assets/Mens/R 23.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,600.00', 'image': 'assets/Mens/R 24.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 4,380.00', 'image': 'assets/Mens/R 25.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,800.00', 'image': 'assets/Mens/R 26.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,700.00', 'image': 'assets/Mens/R 27.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,650.00', 'image': 'assets/Mens/R 28.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,780.00', 'image': 'assets/Mens/R 29.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,870.00', 'image': 'assets/Mens/R 30.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,450.00', 'image': 'assets/Mens/R 31.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,100.00', 'image': 'assets/Mens/R 32.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,990.00', 'image': 'assets/Mens/R 33.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 2,700.00', 'image': 'assets/Mens/R 34.jpg', 'type': 'Trousers'},
  {'name': 'Trousers', 'price': 'LKR 3,660.00', 'image': 'assets/Mens/R 35.jpg', 'type': 'Trousers'},
  {'name': 'T-Shirt', 'price': 'LKR 1,550.00', 'image': 'assets/Mens/T 1.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,660.00', 'image': 'assets/Mens/T 2.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,770.00', 'image': 'assets/Mens/T 3.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,800.00', 'image': 'assets/Mens/T 4.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 2,300.00', 'image': 'assets/Mens/T 5.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,300.00', 'image': 'assets/Mens/T 6.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,400.00', 'image': 'assets/Mens/T 7.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,700.00', 'image': 'assets/Mens/T 8.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,750.00', 'image': 'assets/Mens/T 9.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,700.00', 'image': 'assets/Mens/T 10.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,660.00', 'image': 'assets/Mens/T 11.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,500.00', 'image': 'assets/Mens/T 12.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,800.00', 'image': 'assets/Mens/T 13.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,700.00', 'image': 'assets/Mens/T 14.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,720.00', 'image': 'assets/Mens/T 15.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,780.00', 'image': 'assets/Mens/T 16.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 2,100.00', 'image': 'assets/Mens/T 17.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 2,150.00', 'image': 'assets/Mens/T 18.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 2,250.00', 'image': 'assets/Mens/T 19.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,600.00', 'image': 'assets/Mens/T 20.jpg', 'type': 'T-Shirts'},
  {'name': 'T-Shirts', 'price': 'LKR 1,790.00', 'image': 'assets/Mens/T 21.jpg', 'type': 'T-Shirts'},
  {'name': 'Denims', 'price': 'LKR 2,150.00', 'image': 'assets/Mens/D 1.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 2,350.00', 'image': 'assets/Mens/D 2.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 1,850.00', 'image': 'assets/Mens/D 3.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 1,950.00', 'image': 'assets/Mens/D 3.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 2,750.00', 'image': 'assets/Mens/D 4.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 2,450.00', 'image': 'assets/Mens/D 5.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 2,550.00', 'image': 'assets/Mens/D 6.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 2,500.00', 'image': 'assets/Mens/D 7.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 1,980.00', 'image': 'assets/Mens/D 8.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 2,100.00', 'image': 'assets/Mens/D 9.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 2,400.00', 'image': 'assets/Mens/D 10.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 4,150.00', 'image': 'assets/Mens/D 11.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 3,150.00', 'image': 'assets/Mens/D 12.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 2,750.00', 'image': 'assets/Mens/D 13.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 4,350.00', 'image': 'assets/Mens/D 14.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 4,500.00', 'image': 'assets/Mens/D 15.jpg', 'type': 'Denims'},
  {'name': 'Denims', 'price': 'LKR 3,650.00', 'image': 'assets/Mens/D 16.jpg', 'type': 'Denims'},
  
];
// සපත්තු (Shoes)
final List<Map<String, String>> shoesItems = [
  {'name': 'Heels', 'price': 'LKR 3,850.00', 'image': 'assets/Shoes/H 1.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,700.00', 'image': 'assets/Shoes/H 2.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,750.00', 'image': 'assets/Shoes/H 3.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 2,850.00', 'image': 'assets/Shoes/H 4.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 2,650.00', 'image': 'assets/Shoes/H 5.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,650.00', 'image': 'assets/Shoes/H 6.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,550.00', 'image': 'assets/Shoes/H 7.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 4,150.00', 'image': 'assets/Shoes/H 8.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,350.00', 'image': 'assets/Shoes/H 9.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,650.00', 'image': 'assets/Shoes/H 10.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,850.00', 'image': 'assets/Shoes/H 11.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 1,850.00', 'image': 'assets/Shoes/H 12.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 2,950.00', 'image': 'assets/Shoes/H 13.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,150.00', 'image': 'assets/Shoes/H 14.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 4,100.00', 'image': 'assets/Shoes/H 15.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 2,750.00', 'image': 'assets/Shoes/H 16.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,825.00', 'image': 'assets/Shoes/H 17.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,720.00', 'image': 'assets/Shoes/H 18.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,685.00', 'image': 'assets/Shoes/H 19.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,975.00', 'image': 'assets/Shoes/H 20.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 2,6800.00', 'image': 'assets/Shoes/H 21.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 1,980.00', 'image': 'assets/Shoes/H 22.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 2,650.00', 'image': 'assets/Shoes/H 23.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 2,870.00', 'image': 'assets/Shoes/H 24.jpg', 'type': 'Heels'},
  {'name': 'Heels', 'price': 'LKR 3,850.00', 'image': 'assets/Shoes/H 25.jpg', 'type': 'Heels'},
  {'name': 'Stands', 'price': 'LKR 2,800.00', 'image': 'assets/Shoes/S 1.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 3,1500.00', 'image': 'assets/Shoes/S 2.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 3,2500.00', 'image': 'assets/Shoes/S 3.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 1,950.00', 'image': 'assets/Shoes/S 4.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,760.00', 'image': 'assets/Shoes/S 5.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 4,000.00', 'image': 'assets/Shoes/S 6.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,700.00', 'image': 'assets/Shoes/S 7.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 1,900.00', 'image': 'assets/Shoes/S 8.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 3,800.00', 'image': 'assets/Shoes/S 9.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 1,900.00', 'image': 'assets/Shoes/S 10.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 3,200.00', 'image': 'assets/Shoes/S 11.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 1,900.00', 'image': 'assets/Shoes/S 12.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,600.00', 'image': 'assets/Shoes/S 13.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 3,600.00', 'image': 'assets/Shoes/S 14.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 3,200.00', 'image': 'assets/Shoes/S 15.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 3,100.00', 'image': 'assets/Shoes/S 16.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,600.00', 'image': 'assets/Shoes/S 17.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 1,800.00', 'image': 'assets/Shoes/S 18.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 3,400.00', 'image': 'assets/Shoes/S 19.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 1,980.00', 'image': 'assets/Shoes/S 20.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 1,780.00', 'image': 'assets/Shoes/S 21.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,670.00', 'image': 'assets/Shoes/S 22.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,450.00', 'image': 'assets/Shoes/S 23.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,300.00', 'image': 'assets/Shoes/S 24.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,500.00', 'image': 'assets/Shoes/S 25.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,690.00', 'image': 'assets/Shoes/S 26.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,725.00', 'image': 'assets/Shoes/S 27.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,700.00', 'image': 'assets/Shoes/S 28.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,600.00', 'image': 'assets/Shoes/S 29.jpg', 'type': 'Stands'},
  {'name': 'Stands', 'price': 'LKR 2,900.00', 'image': 'assets/Shoes/S 30.jpg', 'type': 'Stands'},
  {'name': 'Sneakers', 'price': 'LKR 4,200.00', 'image': 'assets/Shoes/SN 1.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,100.00', 'image': 'assets/Shoes/SN 2.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,800.00', 'image': 'assets/Shoes/SN 3.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,500.00', 'image': 'assets/Shoes/SN 4.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 2,900.00', 'image': 'assets/Shoes/SN 5.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,800.00', 'image': 'assets/Shoes/SN 6.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,250.00', 'image': 'assets/Shoes/SN 7.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,300.00', 'image': 'assets/Shoes/SN 8.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,900.00', 'image': 'assets/Shoes/SN 9.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 2,950.00', 'image': 'assets/Shoes/SN 10.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,500.00', 'image': 'assets/Shoes/SN 11.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,700.00', 'image': 'assets/Shoes/SN 12.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 2,600.00', 'image': 'assets/Shoes/SN 13.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 1,900.00', 'image': 'assets/Shoes/SN 14.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 1,8500.00', 'image': 'assets/Shoes/SN 15.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 2,6900.00', 'image': 'assets/Shoes/SN 16.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,200.00', 'image': 'assets/Shoes/SN 17.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,680.00', 'image': 'assets/Shoes/SN 18.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,150.00', 'image': 'assets/Shoes/SN 19.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,550.00', 'image': 'assets/Shoes/SN 20.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,6500.00', 'image': 'assets/Shoes/SN 21.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,700.00', 'image': 'assets/Shoes/SN 22.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,100.00', 'image': 'assets/Shoes/SN 23.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,150.00', 'image': 'assets/Shoes/SN 24.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,500.00', 'image': 'assets/Shoes/SN 25.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,300.00', 'image': 'assets/Shoes/SN 26.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,950.00', 'image': 'assets/Shoes/SN 27.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,670.00', 'image': 'assets/Shoes/SN 28.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,500.00', 'image': 'assets/Shoes/SN 29.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 3,500.00', 'image': 'assets/Shoes/SN 30.jpg', 'type': 'Sneakers'},
  {'name': 'Sneakers', 'price': 'LKR 4,200.00', 'image': 'assets/Shoes/SN 31.jpg', 'type': 'Sneakers'},
  {'name': 'Office Shoes', 'price': 'LKR 5,500.00', 'image': 'assets/Shoes/O 1.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 4,500.00', 'image': 'assets/Shoes/O 2.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 3,500.00', 'image': 'assets/Shoes/O 3.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 3,800.00', 'image': 'assets/Shoes/O 4.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 4,500.00', 'image': 'assets/Shoes/O 5.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 5,400.00', 'image': 'assets/Shoes/O 6.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 5,300.00', 'image': 'assets/Shoes/O 7.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 6,000.00', 'image': 'assets/Shoes/O 9.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 6,100.00', 'image': 'assets/Shoes/O 10.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 5,200.00', 'image': 'assets/Shoes/O 11.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 5,800.00', 'image': 'assets/Shoes/O 12.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 5,600.00', 'image': 'assets/Shoes/O 13.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 4,300.00', 'image': 'assets/Shoes/O 14.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 4,400.00', 'image': 'assets/Shoes/O 15.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 3,500.00', 'image': 'assets/Shoes/O 16.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 3,750.00', 'image': 'assets/Shoes/O 17.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 4,800.00', 'image': 'assets/Shoes/O 19.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 5,500.00', 'image': 'assets/Shoes/O 20.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 4,500.00', 'image': 'assets/Shoes/O 21.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 3,500.00', 'image': 'assets/Shoes/O 22.jpg', 'type': 'Office Shoes'},
  {'name': 'Office Shoes', 'price': 'LKR 4,695.00', 'image': 'assets/Shoes/O 23.jpg', 'type': 'Office Shoes'},
  
];

// ළමා ඇඳුම් සහ සෙල්ලම්බඩු (Kids)
final List<Map<String, String>> kidsItems = [
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,450.00', 'image': 'assets/Kids/BG 1.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,350.00', 'image': 'assets/Kids/BG 2.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,550.00', 'image': 'assets/Kids/BG 3.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,450.00', 'image': 'assets/Kids/BG 4.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,350.00', 'image': 'assets/Kids/BG 5.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,250.00', 'image': 'assets/Kids/BG 6.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 4,500.00', 'image': 'assets/Kids/BG 7.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,650.00', 'image': 'assets/Kids/BG 8.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,750.00', 'image': 'assets/Kids/BG 9.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,850.00', 'image': 'assets/Kids/BG 10.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,650.00', 'image': 'assets/Kids/BG 11.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,750.00', 'image': 'assets/Kids/BG 12.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,350.00', 'image': 'assets/Kids/BG 13.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 1,950.00', 'image': 'assets/Kids/BG 14.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,450.00', 'image': 'assets/Kids/BG 15.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,450.00', 'image': 'assets/Kids/BG 16.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 4,250.00', 'image': 'assets/Kids/BG 17.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 4,150.00', 'image': 'assets/Kids/BG 18.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,550.00', 'image': 'assets/Kids/BG 19.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,850.00', 'image': 'assets/Kids/BG 20.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,450.00', 'image': 'assets/Kids/BG 21.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,950.00', 'image': 'assets/Kids/BG 22.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,450.00', 'image': 'assets/Kids/BG 23.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,650.00', 'image': 'assets/Kids/BG 24.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,350.00', 'image': 'assets/Kids/BG 25.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,550.00', 'image': 'assets/Kids/BG 26.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,650.00', 'image': 'assets/Kids/BG 27.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,750.00', 'image': 'assets/Kids/BG 28.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,850.00', 'image': 'assets/Kids/BG 29.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,950.00', 'image': 'assets/Kids/BG 30.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,350.00', 'image': 'assets/Kids/BG 31.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,425.00', 'image': 'assets/Kids/BG 32.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,975.00', 'image': 'assets/Kids/BG 33.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,250.00', 'image': 'assets/Kids/BG 34.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,350.00', 'image': 'assets/Kids/BG 35.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 4,150.00', 'image': 'assets/Kids/BG 36.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 4,350.00', 'image': 'assets/Kids/BG 37.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,850.00', 'image': 'assets/Kids/BG 38.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,825.00', 'image': 'assets/Kids/BG 39.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,380.00', 'image': 'assets/Kids/BG 40.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,650.00', 'image': 'assets/Kids/BG 41.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,550.00', 'image': 'assets/Kids/BG 43.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,950.00', 'image': 'assets/Kids/BG 44.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 1,990.00', 'image': 'assets/Kids/BG 45.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 1,880.00', 'image': 'assets/Kids/BG 46.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,450.00', 'image': 'assets/Kids/BG 47.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,440.00', 'image': 'assets/Kids/BG 48.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,950.00', 'image': 'assets/Kids/BG 49.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,670.00', 'image': 'assets/Kids/BG 50.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,660.00', 'image': 'assets/Kids/BG 51.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,550.00', 'image': 'assets/Kids/BG 52.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,450.00', 'image': 'assets/Kids/BG 53.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 3,770.00', 'image': 'assets/Kids/BG 54.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 1,990.00', 'image': 'assets/Kids/BG 55.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,770.00', 'image': 'assets/Kids/BG 56.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 4,125.00', 'image': 'assets/Kids/BG 57.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,680.00', 'image': 'assets/Kids/BG 58.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 2,825.00', 'image': 'assets/Kids/BG 59.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Girl Clothes', 'price': 'LKR 1,950.00', 'image': 'assets/Kids/BG 60.jpg', 'type': 'Baby Girl'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,200.00', 'image': 'assets/Kids/BB 1.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 1,900.00', 'image': 'assets/Kids/BB 2.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,300.00', 'image': 'assets/Kids/BB 3.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,400.00', 'image': 'assets/Kids/BB 4.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,500.00', 'image': 'assets/Kids/BB 5.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,525.00', 'image': 'assets/Kids/BB 6.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,690.00', 'image': 'assets/Kids/BB 7.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,710.00', 'image': 'assets/Kids/BB 8.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,8500.00', 'image': 'assets/Kids/BB 9.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 1,800.00', 'image': 'assets/Kids/BB 10.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,700.00', 'image': 'assets/Kids/BB 11.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 1,960.00', 'image': 'assets/Kids/BB 12.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,200.00', 'image': 'assets/Kids/BB 13.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,300.00', 'image': 'assets/Kids/BB 14.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,360.00', 'image': 'assets/Kids/BB 15.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,660.00', 'image': 'assets/Kids/BB 16.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,200.00', 'image': 'assets/Kids/BB 17.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 1,900.00', 'image': 'assets/Kids/BB 18.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,450.00', 'image': 'assets/Kids/BB 19.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,560.00', 'image': 'assets/Kids/BB 20.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,260.00', 'image': 'assets/Kids/BB 21.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,280.00', 'image': 'assets/Kids/BB 22.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,770.00', 'image': 'assets/Kids/BB 23.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,880.00', 'image': 'assets/Kids/BB 24.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,920.00', 'image': 'assets/Kids/BB 25.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,800.00', 'image': 'assets/Kids/BB 26.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,700.00', 'image': 'assets/Kids/BB 27.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 1,960.00', 'image': 'assets/Kids/BB 28.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,200.00', 'image': 'assets/Kids/BB 29.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 4,200.00', 'image': 'assets/Kids/BB 30.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 4,300.00', 'image': 'assets/Kids/BB 31.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 4,400.00', 'image': 'assets/Kids/BB 32.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 4,500.00', 'image': 'assets/Kids/BB 33.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,600.00', 'image': 'assets/Kids/BB 34.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,200.00', 'image': 'assets/Kids/BB 35.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,700.00', 'image': 'assets/Kids/BB 36.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,200.00', 'image': 'assets/Kids/BB 37.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,250.00', 'image': 'assets/Kids/BB 38.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,750.00', 'image': 'assets/Kids/BB 39.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,650.00', 'image': 'assets/Kids/BB 40.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,550.00', 'image': 'assets/Kids/BB 41.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 4,150.00', 'image': 'assets/Kids/BB 42.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 4,6500.00', 'image': 'assets/Kids/BB 43.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 3,270.00', 'image': 'assets/Kids/BB 44.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,200.00', 'image': 'assets/Kids/BB 45.jpg', 'type': 'Baby Boy'},
  {'name': 'Baby Boy Set', 'price': 'LKR 2,500.00', 'image': 'assets/Kids/BB 46.jpg', 'type': 'Baby Boy'},
  {'name': 'Cute Toy', 'price': 'LKR 1,500.00', 'image': 'assets/Kids/T 1.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,600.00', 'image': 'assets/Kids/T 2.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 980.00', 'image': 'assets/Kids/T 3.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,100.00', 'image': 'assets/Kids/T 4.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,400.00', 'image': 'assets/Kids/T 5.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,600.00', 'image': 'assets/Kids/T 6.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,700.00', 'image': 'assets/Kids/T 7.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,650.00', 'image': 'assets/Kids/T 8.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 850.00', 'image': 'assets/Kids/T 9.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 970.00', 'image': 'assets/Kids/T 10.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,300.00', 'image': 'assets/Kids/T 11.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,200.00', 'image': 'assets/Kids/T 12.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,800.00', 'image': 'assets/Kids/T 13.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,680.00', 'image': 'assets/Kids/T 14.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,150.00', 'image': 'assets/Kids/T 15.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,250.00', 'image': 'assets/Kids/T 16.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 750.00', 'image': 'assets/Kids/T 17.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 860.00', 'image': 'assets/Kids/T 18.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,500.00', 'image': 'assets/Kids/T 19.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,900.00', 'image': 'assets/Kids/T 20.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,880.00', 'image': 'assets/Kids/T 21.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,650.00', 'image': 'assets/Kids/T 22.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,500.00', 'image': 'assets/Kids/T 23.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,450.00', 'image': 'assets/Kids/T 24.jpg', 'type': 'Toys'},
  {'name': 'Cute Toy', 'price': 'LKR 1,500.00', 'image': 'assets/Kids/T 25.jpg', 'type': 'Toys'},
  
];

List<Map<String, String>> cartItems = [];